/*
 * generated by Xtext
 */
package eu.netide.sysreq.language.ui.contentassist

import eu.netide.sysreq.language.ui.contentassist.AbstractSystemRequirementsProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class SystemRequirementsProposalProvider extends AbstractSystemRequirementsProposalProvider {
}
