/*
 * generated by Xtext
 */
package eu.netide.telefonica.nemo.ui.contentassist

import eu.netide.telefonica.nemo.ui.contentassist.AbstractNemoDSLProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class NemoDSLProposalProvider extends AbstractNemoDSLProposalProvider {
}
