/*
 * generated by Xtext
 */
package eu.netide.parameters.language;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class NetIDEParametersRuntimeModule extends eu.netide.parameters.language.AbstractNetIDEParametersRuntimeModule {

}
