<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sysreq" nsURI="eu.netide.sysreq" nsPrefix="eu.netide">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="configuration" value="../../eu.netide.configuration/model/Topology.ecore#/"/>
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore#/"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="SystemRequirements">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Root Element"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hardware" lowerBound="1"
        eType="#//Hardware" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="software" lowerBound="1"
        eType="#//Software" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="network" lowerBound="1"
        eType="#//Network" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Network">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="switchtype" ordered="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="of_version" ordered="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="topologyrequirements" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Hardware">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="arch" ordered="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cpucores" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cpufreq" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="800"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="memory" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="512"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Software">
    <eStructuralFeatures xsi:type="ecore:EReference" name="controllers" upperBound="-1"
        eType="#//Controller" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="programminglanguages" upperBound="-1"
        eType="#//ProgrammingLanguage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="libraries" upperBound="-1"
        eType="#//Library" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Controller">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="programminglanguages" ordered="false"
        upperBound="-1" eType="#//ProgrammingLanguage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProgrammingLanguage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Library">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="programminglanguage" lowerBound="1"
        eType="#//ProgrammingLanguage"/>
  </eClassifiers>
</ecore:EPackage>
