<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Topology" nsURI="eu.netide.configuration.topology" nsPrefix="eu.netide.configuration">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="NetworkElement" abstract="true" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="topology" lowerBound="1"
        eType="#//Network" eOpposite="#//Network/networkelements"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ports" lowerBound="1" upperBound="-1"
        eType="#//Port" containment="true" eOpposite="#//Port/networkelement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ip" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dpid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prefix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Switch" eSuperTypes="#//NetworkElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="controller" eType="#//Controller"
        eOpposite="#//Controller/switches"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NetworkEnvironment" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="networks" upperBound="-1"
        eType="#//Network" containment="true" eOpposite="#//Network/networkenvironment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="controllers" upperBound="-1"
        eType="#//Controller" containment="true" eOpposite="#//Controller/networkenvironment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Network" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="networkelements" upperBound="-1"
        eType="#//NetworkElement" containment="true" eOpposite="#//NetworkElement/topology"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="networkenvironment" lowerBound="1"
        eType="#//NetworkEnvironment" eOpposite="#//NetworkEnvironment/networks"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectors" upperBound="-1"
        eType="#//Connector" containment="true" eOpposite="#//Connector/network"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port">
    <eStructuralFeatures xsi:type="ecore:EReference" name="networkelement" lowerBound="1"
        eType="#//NetworkElement" eOpposite="#//NetworkElement/ports"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connector" eType="#//Connector"
        eOpposite="#//Connector/connectedports"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Host" eSuperTypes="#//NetworkElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="nodirectconnection"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="nodirectconnection" value="self.ports&#xA;&#x9;&#x9;&#x9;->forAll(not connector.connectedports->collect(networkelement)->one(p | p &lt;> self).oclIsKindOf(Host))"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connector">
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectedports" ordered="false"
        lowerBound="2" upperBound="2" eType="#//Port" eOpposite="#//Port/connector"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="network" lowerBound="1"
        eType="#//Network" eOpposite="#//Network/connectors"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Controller" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="switches" upperBound="-1"
        eType="#//Switch" eOpposite="#//Switch/controller"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="networkenvironment" lowerBound="1"
        eType="#//NetworkEnvironment" eOpposite="#//NetworkEnvironment/controllers"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ip" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="portNo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
</ecore:EPackage>
