/*
 * generated by Xtext
 */
package eu.netide.ui.contentassist

import eu.netide.ui.contentassist.AbstractParametersProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class ParametersProposalProvider extends AbstractParametersProposalProvider {
}
