/*
 * generated by Xtext 2.10.0
 */
package eu.netide.deployment.topologyvalidation.tests

import com.google.inject.Inject
import eu.netide.deployment.topologyvalidation.flexTopo.ModuleContainer
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(FlexTopoInjectorProvider)
class FlexTopoParsingTest{

	@Inject
	ParseHelper<ModuleContainer> parseHelper

	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
