/*
 * generated by Xtext
 */
package eu.netide.sysreq.language.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SystemRequirementsUiModule extends eu.netide.sysreq.language.ui.AbstractSystemRequirementsUiModule {
	public SystemRequirementsUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
