/*
 * generated by Xtext
 */
package eu.netide.parameters.language.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class NetIDEParametersUiModule extends eu.netide.parameters.language.ui.AbstractNetIDEParametersUiModule {
	public NetIDEParametersUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
