/*
 * generated by Xtext
 */
package eu.netide.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SysReqUiModule extends eu.netide.ui.AbstractSysReqUiModule {
	public SysReqUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
