/*
 * generated by Xtext
 */
package eu.netide.sysreq.language;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SystemRequirementsRuntimeModule extends eu.netide.sysreq.language.AbstractSystemRequirementsRuntimeModule {

}
