/*
* generated by Xtext
*/
package eu.netide.sysreq.language;

import eu.netide.sysreq.language.SystemRequirementsStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SystemRequirementsStandaloneSetup extends SystemRequirementsStandaloneSetupGenerated{

	public static void doSetup() {
		new SystemRequirementsStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

