<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="RuntimeTopology" nsURI="http://eu.netide.runtime.topology" nsPrefix="eu.netide.runtime">
  <eClassifiers xsi:type="ecore:EClass" name="PortStatistics">
    <eStructuralFeatures xsi:type="ecore:EReference" name="runtimedata" lowerBound="1"
        eType="#//RuntimeData" eOpposite="#//RuntimeData/portstatistics"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tx_bytes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rx_bytes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tx_packets" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rx_packets" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tx_errors" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rx_errors" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rx_over_err" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rx_crc_err" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tx_dropped" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rx_dropped" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="collisions" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rx_frame_err" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" lowerBound="1" eType="ecore:EClass ../../eu.netide.configuration/model/Topology.ecore#//Port"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hidden" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RuntimeData">
    <eStructuralFeatures xsi:type="ecore:EReference" name="portstatistics" upperBound="-1"
        eType="#//PortStatistics" containment="true" eOpposite="#//PortStatistics/runtimedata"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="flowstatistics" upperBound="-1"
        eType="#//FlowStatistics" containment="true" eOpposite="#//FlowStatistics/runtimedata"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="networkenvironment" lowerBound="1"
        eType="ecore:EClass ../../eu.netide.configuration/model/Topology.ecore#//NetworkEnvironment"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatedstatistics" upperBound="-1"
        eType="#//AggregatedStatistics" containment="true" eOpposite="#//AggregatedStatistics/runtimedata"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FlowStatistics">
    <eStructuralFeatures xsi:type="ecore:EReference" name="runtimedata" lowerBound="1"
        eType="#//RuntimeData" eOpposite="#//RuntimeData/flowstatistics"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration_sec" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration_nsec" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idle_timeout" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hard_timeout" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cookie" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="packet_count" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="byte_count" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="switch" lowerBound="1"
        eType="ecore:EClass ../../eu.netide.configuration/model/Topology.ecore#//Switch"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hidden" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AggregatedStatistics">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="packet_count" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="byte_count" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="flow_count" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="switch" lowerBound="1"
        eType="ecore:EClass ../../eu.netide.configuration/model/Topology.ecore#//Switch"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hidden" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="runtimedata" lowerBound="1"
        eType="#//RuntimeData" eOpposite="#//RuntimeData/aggregatedstatistics"/>
  </eClassifiers>
</ecore:EPackage>
