<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="RuntimeTopology" nsURI="http://eu.netide.runtime.topology" nsPrefix="eu.netide.runtime">
  <eClassifiers xsi:type="ecore:EClass" name="PortStatistics">
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" lowerBound="1" eType="ecore:EClass ../../eu.netide.configuration/model/Topology.ecore#//Port"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="runtimedata" lowerBound="1"
        eType="#//RuntimeData" eOpposite="#//RuntimeData/portstatistics"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tx_bytes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rx_bytes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RuntimeData">
    <eStructuralFeatures xsi:type="ecore:EReference" name="portstatistics" upperBound="-1"
        eType="#//PortStatistics" containment="true" eOpposite="#//PortStatistics/runtimedata"/>
  </eClassifiers>
</ecore:EPackage>
