/*
 * generated by Xtext
 */
package eu.netide.parameters.language.ui.contentassist

import eu.netide.parameters.language.ui.contentassist.AbstractNetIDEParametersProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class NetIDEParametersProposalProvider extends AbstractNetIDEParametersProposalProvider {
}
