/*
 * generated by Xtext
 */
package eu.netide;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ParametersRuntimeModule extends eu.netide.AbstractParametersRuntimeModule {

}
