/*
 * generated by Xtext
 */
package eu.netide.telefonica.nemo;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class NemoDSLStandaloneSetup extends NemoDSLStandaloneSetupGenerated{

	public static void doSetup() {
		new NemoDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

