/*
 * generated by Xtext
 */
package eu.netide.telefonica.nemo;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class NemoDSLRuntimeModule extends eu.netide.telefonica.nemo.AbstractNemoDSLRuntimeModule {

}
