/*
 * generated by Xtext
 */
package eu.netide.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ParametersUiModule extends eu.netide.ui.AbstractParametersUiModule {
	public ParametersUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
