/*
 * generated by Xtext
 */
package eu.netide.telefonica.nemo.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator;

/**
 * Use this class to register components to be used within the IDE.
 */
public class NemoDSLUiModule extends eu.netide.telefonica.nemo.ui.AbstractNemoDSLUiModule {
	public NemoDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
//	public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration() {
//		return NemoDSLHighlightingConfiguration.class;
//	}
	public Class<? extends ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator(){
		return NemoDSLHighlightingCalculator.class;
	}
}
